server:
    port: 8080
etablissement:
    siret:
        31302979500017,
        41339442000033,
        41339442000090,
        41339442000116,
        41776304200013,
        43438147100011,
        45251723800013,
        52170053400014,
        75254783600011,
        47962817400042,
        97080195700014
api-insee:
    authorization-bearer: b7ccc1c9-bfbe-3734-a25d-0b16705c6923
    endpoint-sirene: https://api.insee.fr/entreprises/sirene/V3
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        open-in-view: off
    h2:
        console:
            enabled: true
            path: /h2-ui